### PR TITLE
Repository Overhaul

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `mod`
  - `raft`
  - `inventory`
  - `storage`

  <br>

- **Update Description**

  `Raft mod to quickly Inventory ➞ Storage.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- Added editorconfig

- Formatted README , manifest

- Refactored code

  *Please check*

- Added license badge

- Referenced links

- Added quicklink

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/QuickStackInventory

### CODE REVIEW

**Comment by MahmoudOkasha17** [comment]
Well, have u tested running the mod after these changes? , I noticed you're using dynamic type, and I was getting the error here https://forum.unity.com/threads/using-dynamic-keyword-not-working.490600/ when I tried it before, and I didn't bother looking for a solution. , also, is there a specific reason you decided to separate some of the if conditions? , I don't mind the change, but was wondering if there was a specific reason for it

**Comment by ElectronicsArchiver** [comment]
> Well, have u tested running the mod after these changes? 

Running, no, I'm on a Linux system and I can't even 
seem to get started with testing it on here~

That's why I was asking you to try it ;)

Syntax wise it should be fine, my editor
can at least verify that much..

>  I noticed you're using dynamic type

Sorry my mistake, yes you can apparently 
fix the editor assemblies, no I don't 
know the specifics.

> is there a specific reason you decided to separate some of the if conditions?

Yes, a great many.

For one you should always try to avoid nesting
and combined conditions to simplify the logic.

A sequence is easier to understand than a tree.

Of course the code could be refactored even
better if the bigger section were also split
up into smaller functions.

In general programmers spend more time reading 
code than writing it so reducing said effort 
is rather important~

**Comment by ElectronicsArchiver** [comment]
@MahmoudOkasha17 It's been a week..

**Comment by MahmoudOkasha17** [comment]
Sorry for the late response, I didn't have free time to test, and it is working fine, just had 1 error for a variable named incorrectly, I will merge and fix it, thanks for yours suggestions <3

**Pull request merged**
